FROM mkubatovic/mavenm2:latest as BUILD_IMAGE

COPY ./target/employees.jar . \
    ./pom.xml ./

RUN mvn clean package

FROM openjdk:8-jdk-alpine

COPY --from=BUILD_IMAGE employees.jar .
EXPOSE 8080
CMD java -jar employees.jar
