FROM openjdk:8-jdk-alpine AS BUILD_IMAGE

RUN apk add --no-cache curl tar bash git openssh-server openssh-client

#Installing Maven and setting up ARGs
ARG MAVEN_VERSION=3.5.0
ARG USER_HOME_DIR="/root"
ARG SHA=beb91419245395bd69a4a6edad5ca3ec1a8b64e41457672dc687c173a495f034
ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries
ARG APP_HOME=/root/app/
ARG ssh_prv_key
ARG ssh_pub_key

RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
  && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  && echo "${SHA}  /tmp/apache-maven.tar.gz" | sha256sum -c - \
  && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
  && rm -f /tmp/apache-maven.tar.gz \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"

VOLUME "$USER_HOME_DIR/.m2"

#Setting up SSH keys for git

# Authorize SSH Host
RUN mkdir -p /root/.ssh && \
    chmod 0700 /root/.ssh && \
    ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts

# Add the keys and set permissions
RUN echo "$ssh_prv_key" > /root/.ssh/id_rsa && \
    echo "$ssh_pub_key" > /root/.ssh/id_rsa.pub && \
    chmod 600 /root/.ssh/id_rsa && \
    chmod 600 /root/.ssh/id_rsa.pub




#Giting the needed files


WORKDIR $APP_HOME
RUN git clone git@github.com:mlrdk/employeeslist.git
RUN rm -rf /root/.ssh


#Running Maven

ENTRYPOINT ["mvn","clean","install"]

#Runing the app

FROM openjdk:8-jdk-alpine
WORKDIR /root/
COPY --from=BUILD_IMAGE /root/app/target/Employees.jar .
EXPOSE 8080
CMD ["java","-jar","Employees.jar"]
