FROM mkubatovic/mavenm2git:latest as BUILD_IMAGE

RUN apk add --no-cache bash git openssh-server openssh-client

RUN mkdir  /root/.ssh && \
    chmod 0700 /root/.ssh && \
    ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts

COPY sshkeys ./root/.ssh

RUN chmod 600 /root/.ssh/id_rsa && \
    chmod 600 /root/.ssh/id_rsa.pub

RUN mkdir /sources \
    && cd /sources \
    && git clone git@github.com:mlrdk/employeeslist.git . \
    && mvn clean package \
    && cd / \
    && rm -rf /root/.ssh


FROM openjdk:8-jdk-alpine

COPY --from=BUILD_IMAGE /sources/target/employees.jar .
EXPOSE 8080
ENTRYPOINT java -jar employees.jar
