FROM mkubatovic/maven:5.2.0

RUN apk add --no-cache bash git openssh-server openssh-client

#SSH SETUP

RUN mkdir -p /root/.ssh && \
    chmod 0700 /root/.ssh && \
    ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts

COPY ./sshkeys/ /root/.ssh/

RUN chmod 600 /root/.ssh/id_rsa && \
    chmod 600 /root/.ssh/id_rsa.pub

RUN git clone