FROM openjdk:8-jdk-alpine AS BUILD_IMAGE

RUN apk add --no-cache curl tar bash

#Installing Maven and setting up ARGs
ARG USER_HOME_DIR="/root"
ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/3.5.2/binaries
ARG APP_HOME=/root/app/
ARG SHA=beb91419245395bd69a4a6edad5ca3ec1a8b64e41457672dc687c173a495f034
ARG MAVEN_VERSION=3.5.2

RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
  && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-3.5.2-bin.tar.gz \
  && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
  && rm -f /tmp/apache-maven.tar.gz \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn


ENV MAVEN_HOME /usr/share/maven \
    PATH=/usr/share/maven/bin:$PATH \
    MAVEN_CONFIG "$USER_HOME_DIR/.m2"

